version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: ./src/Household.Api.Server/Dockerfile
        ports:
        -   "8080:80"
        depends_on:
            -   recipes
        networks:
            - cookbook
    web_dapr:
        image: "daprio/daprd:edge"
        command: [ "./daprd",
                   "-app-id", "web",
                   "-app-port", "8080"  ]
        depends_on:
            - recipes
        network_mode: "service:web"

    recipes:
        build:
            context: .
            dockerfile: ./src/Household.Recipes/Dockerfile
        ports:
            - "5040:80"
        networks:
            - cookbook
    recipes_dapr:
        image: "daprio/daprd:edge"
        command: [ "./daprd",
                   "-app-id", "recipes",
                   "-app-port", "5040" ]
        depends_on:
            - recipes
        network_mode: "service:recipes"
networks:
    cookbook: