name: Azure ARM build
on:
    workflow_dispatch:

    push:
        branches: [ master ]
        paths:
            - 'Infrastructure.fsx'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 5.0.100

            -   name: Install dependencies
                run: dotnet tool restore

            -   name: Build
                run: dotnet fake build -p -t ArmTemplate
                env:
                    environment: dev
                    subscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
                    clientId: ${{ secrets.AZURECLIENTID }}
                    clientSecret: ${{ secrets.AZURECLIENTSECRET }}
                    tenantId: ${{ secrets.AZURETENANTID }}
