name: Build docker image

on:
    workflow_dispatch:

    push:
        branches: [ master ]
        paths-ignore:
            - 'Infrastructure.fs'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Docker cache
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: build docker image
                uses: docker/build-push-action@v2
                with:
                    context: ./
                    file: ./Dockerfile
                    builder: ${{ steps.buildx.outputs.name }}
                    push: true
                    tags: landys/cookbook:latest
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache






