name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet tool restore
    - name: restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet fake build -t AppService
      env:
          environment: dev
          subscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
          clientId: ${{ secrets.AZURECLIENTID }}
          clientSecret: ${{ secrets.AZURECLIENTSECRET }}
          tenantId: ${{ secrets.AZURETENANTID }}



